"""
Django settings for socialLogin project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q3@s-e^&gs@k)u@3a!ggcprbcas@3x%b2k9qjplo_-dydoefv7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'login',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    # 'allauth.socialaccount.providers.linkedin',
    'allauth.socialaccount.providers.twitter',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'socialLogin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialLogin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'social_core.backends.linkedin.LinkedinOAuth2',
    # 'allauth.socialaccount.providers.oauth.provider.OAuthProvider',
    # 'allauth.socialaccount.providers.twitter.auth.TwitterOAuthAdapter',
    # 'allauth.socialaccount.providers.twitter.provider.TwitterProvider'
]
SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE' : [
            'profile',
            'email'
        ],
        'APP': {
            'client_id': '375273379942-ooc3jtnsmov0qo8gt5obiukdsfjugfl8.apps.googleusercontent.com',
            'secret': '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',
            'key' : '',
        },
        'AUTH_PARAMS': {
            'access_type':'online',
        }
    },
    'facebook': {
        'APP': {
            'client_id': '339213185798864',
            'secret': '946a15608bf0ce92f3442c27a7d56241',
            'key' : '',
        },
    },

    'github': {
        'APP': {
            'client_id': '027b38c294a869e2eced',
            'secret': '44b495786871973f2f8dab26f7a4622371b2e7cf',
            'key' : '',
        },
    },

    'twitter': {
        'APP':{
            'client_id': 'dFVUWFV6MzVHdEFYRWs4ejBva0s6MTpjaQ',
            'secret': '-SLyGhPJLs57S-tuK6EKq3TCNLJs5PWZ4l2BENnyWpQcKI5UFV'
        }
    },
    'linkedin-oauth2': {
        'APP': {
            'client_id': '86a665juyylktl',
            'secret': 'MHOj30wAh3JsiHGJ',
            'key' : '',
        },
    }
    # 'linkedin_oauth2': {
    #      'APP': {
    #         'client_id': '86a665juyylktl',
    #         'secret': 'MHOj30wAh3JsiHGJ',
    #         'key': '',
    #     },
    #       'SCOPE': [
    #         'r_liteprofile',
    #         'r_emailaddress',
    #         'w_member_social',
    #     ],
    #      'PROFILE_FIELDS': [
    #         'id',
    #         'firstName',
    #         'lastName',
    #         'emailAddress',
    #         'email-address',
    #         'profilePicture',
    #         'public-profile-url',
    #     ],
    #     'LOCATION_FIELDS': [
    #         'location',
    #     ],
    #     'POSITION_FIELDS': [
    #         'company',
    #     ]
    # },
    
}


	
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = 'home'

# SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '86a665juyylktl'
# SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'MHOj30wAh3JsiHGJ'

# SOCIAL_AUTH_TWITTER_KEY = 'dFVUWFV6MzVHdEFYRWs4ejBva0s6MTpjaQ' 
# SOCIAL_AUTH_TWITTER_SECRET = '-SLyGhPJLs57S-tuK6EKq3TCNLJs5PWZ4l2BENnyWpQcKI5UFV'

# XyuUI7rThXWiC7JBSlBggbnVb apikey
# Sz3bWXZAzvSSRYH7at6kZaCs11Uk8n2r87W1KKbxCU889fmMJ9 apisecretkey